import Foundation

/// Teksty interfejsu (pl/en) — odpowiednik Strings.pl.xaml / Strings.en.xaml z wersji Windows.
///
/// Celowo w kodzie, a nie w zasobach pakietu: zasoby SwiftPM w ręcznie składanej paczce .app trzeba
/// by kłaść w katalogu głównym .app, co psuje podpis. Przy okazji test parzystości (pl ↔ en) działa
/// zwykłym `swift test`, także na Linuksie.
public enum Strings {
    public static let pl: [String: String] = [
        "menu.newserver": "Nowy serwer…",
        "menu.import": "Importuj z Waypoint dla Windows…",

        "list.search": "Szukaj serwera",
        "list.pinned": "Przypięte",
        "list.ungrouped": "Bez grupy",
        "list.copyname": "%@ (kopia)",

        "act.connect": "Połącz",
        "act.edit": "Edytuj…",
        "act.duplicate": "Duplikuj",
        "act.pin": "Przypnij",
        "act.unpin": "Odepnij",
        "act.copyhost": "Kopiuj adres",
        "act.delete": "Usuń…",

        "del.title": "Usunąć serwer?",
        "del.msg": "„%@” zniknie z listy. Tego nie da się cofnąć.",
        "del.confirm": "Usuń",

        "empty.title": "Brak serwerów",
        "empty.desc": "Dodaj pierwszy serwer albo zaimportuj listę z Waypointa dla Windows (Ustawienia → Eksportuj profil…).",
        "detail.none": "Wybierz serwer z listy",
        "detail.unsupported": "Ten rodzaj połączenia działa na razie tylko w wersji Windows. Wpis zostaje na liście, żeby import niczego nie gubił.",

        "f.name": "Nazwa",
        "f.name.ph": "np. Produkcja — web",
        "f.protocol": "Protokół",
        "f.protocol.win": "tylko Windows",
        "f.host": "Adres",
        "f.port": "Port",
        "f.user": "Użytkownik",
        "f.domain": "Domena",
        "f.key": "Klucz prywatny",
        "f.group": "Grupa",
        "f.group.ph": "np. Produkcja",
        "f.group.pick": "Wybierz istniejącą grupę",
        "f.tags": "Tagi",
        "f.tags.ph": "oddzielone przecinkami",
        "f.pinned": "Przypięty na górze listy",
        "f.tunnels": "Tunele",
        "f.tunnels.hint": "Jak ssh -L: portLokalny:host:portZdalny, po jednym w wierszu.",
        "f.notes": "Notatki",
        "f.ftpenc": "Szyfrowanie",
        "f.ftpenc.explicit": "Jawne FTPS (zalecane)",
        "f.ftpenc.implicit": "Niejawne FTPS",
        "f.ftpenc.none": "Brak (zwykły FTP)",
        "f.ftpanon": "Logowanie anonimowe",

        "edit.sec.login": "Logowanie",
        "edit.sec.org": "Porządek",
        "edit.choose": "Wybierz…",
        "edit.err.host": "Podaj adres serwera.",
        "edit.err.hostspace": "Adres nie może zawierać spacji.",
        "edit.err.port": "Port musi być liczbą od 1 do 65535.",

        "btn.cancel": "Anuluj",
        "btn.add": "Dodaj",
        "btn.save": "Zapisz",

        "import.title": "Import serwerów",
        "import.message": "Wybierz plik profilu wyeksportowany z Waypointa dla Windows albo servers.json.",
        "import.done.title": "Zaimportowano",
        "import.done.msg": "Nowe serwery: %ld, zaktualizowane: %ld. Hasła nie są przenoszone — podasz je przy pierwszym połączeniu.",
        "import.err.empty": "Plik nie zawiera żadnych serwerów.",
        "import.err.format": "To nie jest plik profilu Waypointa ani lista serwerów.",

        "alert.corrupt.title": "Nie udało się odczytać listy serwerów",
        "alert.corrupt.msg": "Uszkodzony plik został odłożony jako:\n%@\nLista została odtworzona z kopii zapasowej (jeśli była).",
        "alert.save.title": "Nie udało się zapisać listy serwerów",

        "connect.notyet": "Łączenie tym protokołem pojawi się w jednym z kolejnych kroków.",

        "ssh.warn.winkey": "Ścieżka klucza pochodzi z Windows i nie istnieje na tym Macu — ssh spróbuje kluczy z agenta i domyślnych. Popraw ją w edycji serwera.",
        "ssh.warn.nokey": "Nie znaleziono pliku klucza wskazanego w serwerze — ssh spróbuje kluczy z agenta i domyślnych.",
        "ssh.warn.tunnel": "Pominięto tunel o niepoprawnym formacie (oczekiwane portLokalny:host:portZdalny).",

        "tab.close": "Zamknij kartę",
        "tab.reconnect": "Połącz ponownie",
        "close.title": "Zamknąć „%@”?",
        "close.msg": "Połączenie jest aktywne — zostanie zakończone.",
        "close.confirm": "Zamknij",
        "quit.title": "Zakończyć Waypoint?",
        "quit.msg": "Aktywne połączenia: %ld. Wszystkie zostaną zakończone.",
        "quit.confirm": "Zakończ",
        "ended.clean": "Połączenie zakończone",
        "ended.code": "Połączenie przerwane (kod %@)",

        "prompt.password": "Hasło do %@",
        "prompt.passphrase": "Hasło klucza prywatnego",
        "prompt.hostkey": "Nieznany klucz serwera",
        "prompt.other": "%@ pyta",
        "prompt.retry": "Poprzednie hasło zostało odrzucone.",
        "prompt.save": "Zapisz w Pęku kluczy",
        "prompt.login": "Zaloguj",
        "prompt.yes": "Ufaj i połącz",
        "prompt.no": "Przerwij",
        "prompt.saved": "Hasło zapisane w Pęku kluczy",
        "prompt.savefail": "Nie udało się zapisać hasła w Pęku kluczy",

        "detail.password": "Hasło",
        "detail.password.saved": "zapisane w Pęku kluczy",
        "detail.password.forget": "Zapomnij",

        "rdp.opened": "Otwarto w Windows App — hasło podaj tam (Windows App zapamięta je u siebie).",
        "rdp.missing.title": "Brak aplikacji Windows App",
        "rdp.missing.msg": "Na Macu połączenia RDP otwiera darmowa aplikacja Microsoft Windows App (dawniej Microsoft Remote Desktop). Zainstaluj ją z App Store i połącz ponownie.",
        "rdp.missing.store": "Otwórz App Store",
        "rdp.export": "Eksportuj plik .rdp…",
        "rdp.import": "Importuj plik .rdp…",
        "btn.close": "Zamknij",
        "edit.sec.rdp": "Pulpit zdalny",
        "f.rdp.clipboard": "Udostępniaj schowek",
        "f.rdp.drives": "Udostępniaj dyski",
        "f.rdp.admin": "Sesja administracyjna (/admin)",
        "f.rdp.auth": "Certyfikat serwera",
        "f.rdp.auth.warn": "Ostrzegaj (zalecane)",
        "f.rdp.auth.require": "Wymagaj poprawnego",
        "f.rdp.auth.none": "Nie sprawdzaj",
        "f.rdp.gateway": "Brama RD",
        "f.rdp.app": "RemoteApp",
        "f.rdp.app.ph": "program albo ||alias (puste = pulpit)",
        "f.rdp.hint": "Połączenie otwiera Microsoft Windows App. Te same ustawienia czyta wersja Windows.",

        "act.files": "Pliki (SFTP)",
        "files.connecting": "Łączenie…",
        "files.failed": "Nie udało się połączyć",
        "files.cancelled": "Anulowano",
        "files.up": "Katalog wyżej",
        "files.refresh": "Odśwież",
        "files.newfolder": "Nowy folder",
        "files.newfolder.ph": "Nazwa folderu",
        "files.upload": "Wyślij…",
        "files.upload.button": "Wyślij",
        "files.download": "Pobierz…",
        "files.download.button": "Pobierz tutaj",
        "files.delete": "Usuń…",
        "files.rename": "Zmień nazwę",
        "files.open": "Otwórz",
        "files.openfolder": "Otwórz folder",
        "files.copypath": "Kopiuj ścieżkę",
        "files.col.name": "Nazwa",
        "files.col.size": "Rozmiar",
        "files.col.modified": "Zmodyfikowano",
        "files.col.mode": "Uprawnienia",
        "files.count": "Elementów: %ld",
        "files.items": "%ld elementów",
        "files.uploading": "Wysyłanie: %@",
        "files.uploaded": "Wysłano: %@",
        "files.downloading": "Pobieranie: %@",
        "files.downloaded": "Pobrano %@ do %@",
        "files.deleting": "Usuwanie…",
        "files.deleted": "Usunięto elementów: %ld",
        "files.delete.one": "Usunąć „%@”?",
        "files.delete.many": "Usunąć %ld elementów?",
        "files.delete.msg": "Foldery zostaną usunięte razem z zawartością. Tego nie da się cofnąć.",
        "files.overwrite.title": "Nadpisać istniejące?",
        "files.overwrite.msg": "W tym katalogu już są: %@. Nadpisać je?",
        "files.overwrite.confirm": "Nadpisz",
        "files.err.denied": "Brak uprawnień.",
        "files.err.missing": "Nie ma takiego pliku ani katalogu.",
        "files.err.disconnected": "Połączenie zostało przerwane.",
        "files.err.name": "Nazwa nie może być pusta ani zawierać „/”.",
        "files.err.exists": "„%@” już istnieje w tym katalogu.",

        "files.edit": "Edytuj w Waypoint  ⌘E",
        "edit.loading": "Wczytywanie edytora…",
        "edit.wrap": "Zawijanie wierszy",
        "edit.reload": "Wczytaj ponownie z serwera",
        "edit.savecopy": "Zapisz kopię na dysku…",
        "edit.yes": "Tak",
        "edit.discard": "Nie zapisuj",
        "edit.ro.text": "Plik należy do %@ i ma uprawnienia %@ — Twoje konto najpewniej nie może go zmienić, więc otwarto go tylko do odczytu. Możesz edytować i zapisywać przez sudo albo zapisać kopię na dysku.",
        "edit.ro.anyway": "Edytuj mimo to",
        "edit.ro.status": "Plik jest otwarty tylko do odczytu.",
        "edit.ro.short": "tylko odczyt",
        "edit.note.latin1": "Plik nie jest w UTF-8 — otwarto go jako Latin-1; zapis zachowa to kodowanie.",
        "edit.note.mixed": "Plik ma mieszane końce linii — zapis ujednolici je do %@.",
        "edit.shutdown": "Niezapisane zmiany w otwartych edytorach: %ld. Zakończyć bez zapisywania?",
        "edit.latin1.ask": "Znaku „%@” nie da się zapisać w kodowaniu Latin-1, w którym jest ten plik. Zapisać plik jako UTF-8?",
        "edit.nochange": "Bez zmian — nie było czego zapisywać.",
        "edit.saving": "Zapisywanie…",
        "edit.conflict": "„%@” zmienił się na serwerze od chwili otwarcia (teraz: %@, %@). Zapis nadpisze tamte zmiany. Zapisać mimo to?",
        "edit.conflict.kept": "Nie zapisano — plik na serwerze zmienił się w międzyczasie. Twoja wersja jest w edytorze.",
        "edit.saved": "Zapisano %@.",
        "edit.saved.inplace": "Zapisano %@ — w miejscu, bo %@.",
        "edit.fb.dir": "nie ma prawa zapisu do katalogu",
        "edit.fb.owner": "podmiana zmieniłaby właściciela pliku",
        "edit.fb.group": "podmiana zmieniłaby grupę pliku",
        "edit.fb.rename": "serwer nie obsługuje atomowej podmiany",
        "edit.fail.denied": "Brak uprawnień do zapisu tego pliku. Plik na serwerze jest nietknięty, a Twoje zmiany zostały w edytorze.\n\nPrzy serwerach SSH możesz zapisać przez sudo (pasek u góry albo ponowny zapis). Możesz też zapisać kopię na dysku.",
        "edit.fail.safe": "Nie udało się zapisać: %@\n\nPlik na serwerze jest nietknięty. Twoje zmiany zostały w edytorze — możesz ponowić zapis (⌘S).",
        "edit.fail.damaged": "Zapis przerwał się w trakcie: %@\n\nPlik na serwerze mógł zostać ucięty! Twoja pełna wersja jest w edytorze — ponów zapis (⌘S), gdy połączenie wróci, albo zapisz kopię na dysku.",
        "edit.fail.short": "Nie zapisano — plik na serwerze nietknięty.",
        "edit.fail.damaged.short": "Zapis przerwany — plik na serwerze mógł zostać ucięty. Ponów zapis.",
        "edit.copysaved": "Zapisano kopię: %@",
        "edit.reload.ask": "Wczytać plik ponownie z serwera? Niezapisane zmiany przepadną.",
        "edit.reloading": "Wczytywanie z serwera…",
        "edit.reloaded": "Wczytano z serwera %@.",
        "edit.close.ask": "Zapisać zmiany w „%@” przed zamknięciem?",
        "edit.toobig": "Plik jest za duży do edycji (limit %@). Pobierz go albo otwórz w innej aplikacji.",
        "edit.binary": "To plik binarny — edytor obsługuje tylko pliki tekstowe.",
        "edit.pos": "Wiersz %ld, kol. %ld",
        "edit.sel": "(zaznaczono %ld)",

        "edit.ro.sudo": "Edytuj i zapisuj przez sudo",
        "edit.sudo.short": "sudo",

        "menu.go": "Przejdź",
        "menu.terminal": "Terminal",
        "pal.open": "Paleta poleceń…",
        "pal.placeholder": "Serwer, karta, akcja albo user@host do szybkiego połączenia",
        "pal.tabs": "Karta",
        "pal.servers": "Serwer",
        "pal.actions": "Akcja",
        "pal.quick": "Połącz z „%@”",
        "pal.quick.section": "Szybkie połączenie",
        "pal.quickmenu": "Szybkie połączenie…",
        "snip.title": "Snippety",
        "snip.menu.pick": "Wyślij snippet…",
        "snip.menu.manage": "Zarządzaj snippetami…",
        "snip.filter": "Szukaj snippetu",
        "snip.empty": "Brak snippetów",
        "snip.empty.desc": "Snippet to zapisana komenda wysyłana do terminala jednym skrótem, ze zmiennymi serwera: {host}, {user}…",
        "snip.noterminal": "Brak aktywnego terminala",
        "snip.target": "Do: %@",
        "snip.noenter": "Bez Enter — tylko wpisuje",
        "snip.new": "Nowy snippet",
        "snip.name": "Nazwa",
        "snip.command": "Komenda",
        "snip.vars": "Zmienne:",
        "snip.sendenter": "Wyślij Enter na końcu",
        "snip.hint": "⌥⌘1…9 wysyła snippet o tym numerze",
        "tab.duplicate": "Duplikuj kartę",
        "term.find": "Znajdź w terminalu…",
        "term.zoomin": "Powiększ czcionkę",
        "term.zoomout": "Pomniejsz czcionkę",
        "term.zoomreset": "Domyślny rozmiar czcionki",
        "edit.sudo.ask": "Twoje konto nie może zapisać tego pliku. Zapisać go jako root przez sudo? Właściciel i uprawnienia pliku zostaną zachowane.",
        "edit.sudo.yes": "Zapisz przez sudo",
        "edit.sudo.saving": "Zapisywanie przez sudo…",
        "edit.sudo.saved": "Zapisano %@ przez sudo.",
        "edit.sudo.saved.inplace": "Zapisano %@ przez sudo — w miejscu (serwer bez GNU coreutils albo bez miejsca na plik obok).",
        "edit.sudo.prompt": "[sudo] hasło użytkownika %@ na %@",

        "edit.fb.ftp": "FTP nie ma atomowej podmiany",
        "files.err.cancelledLogin": "Logowanie anulowane.",
        "files.err.login": "Serwer odrzucił login lub hasło.",
        "files.err.cert": "Nie można zweryfikować certyfikatu serwera (%@). Jeśli to Twój serwer z certyfikatem samopodpisanym, możesz mu zaufać.",
        "files.cert.trust": "Ufaj certyfikatowi tego serwera",
        "files.cert.trust.help": "Połączenie dalej będzie szyfrowane, ale bez sprawdzania, kto wystawił certyfikat. Zgoda dotyczy tylko tego serwera.",

        "btn.ok": "OK",
        "group.rename": "Zmień nazwę grupy…",
        "group.rename.title": "Zmień nazwę grupy",
        "group.rename.msg": "Nowa nazwa dla „%@” (zmieni się we wszystkich jej serwerach):",
        "group.collapse": "Zwiń",
        "group.expand": "Rozwiń",
        "group.moveto": "Przenieś do grupy",
        "group.new": "Nowa grupa…",
        "group.new.title": "Nowa grupa",
        "group.new.msg": "Nazwa grupy:",
        "reach.online": "Osiągalny · %d ms",
        "reach.online.short": "Osiągalny",
        "reach.offline": "Nieosiągalny",
        "dash.title": "Pulpit",
        "dash.servers": "Serwery",
        "dash.online": "Osiągalne",
        "dash.connects": "Połączenia (%d dni)",
        "dash.quick.placeholder": "Szybkie połączenie: user@host[:port] (port 3389 = RDP)",
        "dash.recent": "Ostatnio używane",
        "dash.recent.help": "Połącz z %@",
        "dash.activity": "Aktywność — ostatnie %d dni",
        "dash.day": "Dzień",
        "dash.count": "Połączenia",
        "dash.top": "Najczęściej używane",
        "log.reveal": "Pokaż dziennik połączeń",
        "log.empty": "Dziennik połączeń jest jeszcze pusty",
        "set.list": "Lista serwerów",
        "set.reach": "Sprawdzaj osiągalność serwerów w tle",
        "set.reach.interval": "Co ile",
        "set.reach.timeout": "Limit czasu sondy",
        "set.seconds": "%d s",
        "set.latency": "Pokazuj opóźnienie (ms) na liście",
        "set.connections": "Połączenia",
        "set.confirmclose": "Pytaj przed zamknięciem aktywnego połączenia",
        "set.log": "Zapisuj dziennik połączeń (bez haseł)",
    ]

    public static let en: [String: String] = [
        "menu.newserver": "New Server…",
        "menu.import": "Import from Waypoint for Windows…",

        "list.search": "Search servers",
        "list.pinned": "Pinned",
        "list.ungrouped": "No group",
        "list.copyname": "%@ (copy)",

        "act.connect": "Connect",
        "act.edit": "Edit…",
        "act.duplicate": "Duplicate",
        "act.pin": "Pin",
        "act.unpin": "Unpin",
        "act.copyhost": "Copy Address",
        "act.delete": "Delete…",

        "del.title": "Delete server?",
        "del.msg": "“%@” will be removed from the list. This cannot be undone.",
        "del.confirm": "Delete",

        "empty.title": "No servers",
        "empty.desc": "Add your first server or import the list from Waypoint for Windows (Settings → Export profile…).",
        "detail.none": "Select a server",
        "detail.unsupported": "This connection type currently works only in the Windows version. The entry stays on the list so importing loses nothing.",

        "f.name": "Name",
        "f.name.ph": "e.g. Production — web",
        "f.protocol": "Protocol",
        "f.protocol.win": "Windows only",
        "f.host": "Address",
        "f.port": "Port",
        "f.user": "User",
        "f.domain": "Domain",
        "f.key": "Private key",
        "f.group": "Group",
        "f.group.ph": "e.g. Production",
        "f.group.pick": "Choose an existing group",
        "f.tags": "Tags",
        "f.tags.ph": "comma-separated",
        "f.pinned": "Pinned to the top of the list",
        "f.tunnels": "Tunnels",
        "f.tunnels.hint": "Like ssh -L: localPort:host:remotePort, one per line.",
        "f.notes": "Notes",
        "f.ftpenc": "Encryption",
        "f.ftpenc.explicit": "Explicit FTPS (recommended)",
        "f.ftpenc.implicit": "Implicit FTPS",
        "f.ftpenc.none": "None (plain FTP)",
        "f.ftpanon": "Anonymous login",

        "edit.sec.login": "Login",
        "edit.sec.org": "Organization",
        "edit.choose": "Choose…",
        "edit.err.host": "Enter the server address.",
        "edit.err.hostspace": "The address cannot contain spaces.",
        "edit.err.port": "Port must be a number from 1 to 65535.",

        "btn.cancel": "Cancel",
        "btn.add": "Add",
        "btn.save": "Save",

        "import.title": "Import servers",
        "import.message": "Choose a profile file exported from Waypoint for Windows, or servers.json.",
        "import.done.title": "Imported",
        "import.done.msg": "New servers: %ld, updated: %ld. Passwords are not transferred — you will enter them on first connect.",
        "import.err.empty": "The file contains no servers.",
        "import.err.format": "This is not a Waypoint profile or server list.",

        "alert.corrupt.title": "Could not read the server list",
        "alert.corrupt.msg": "The damaged file was moved aside as:\n%@\nThe list was restored from the backup (if there was one).",
        "alert.save.title": "Could not save the server list",

        "connect.notyet": "Connecting with this protocol is coming in one of the next steps.",

        "ssh.warn.winkey": "The key path comes from Windows and does not exist on this Mac — ssh will try agent and default keys. Fix it in the server settings.",
        "ssh.warn.nokey": "The key file set for this server was not found — ssh will try agent and default keys.",
        "ssh.warn.tunnel": "Skipped a tunnel with an invalid format (expected localPort:host:remotePort).",

        "tab.close": "Close Tab",
        "tab.reconnect": "Reconnect",
        "close.title": "Close “%@”?",
        "close.msg": "The connection is active and will be ended.",
        "close.confirm": "Close",
        "quit.title": "Quit Waypoint?",
        "quit.msg": "Active connections: %ld. All of them will be ended.",
        "quit.confirm": "Quit",
        "ended.clean": "Connection closed",
        "ended.code": "Connection lost (code %@)",

        "prompt.password": "Password for %@",
        "prompt.passphrase": "Private key passphrase",
        "prompt.hostkey": "Unknown server key",
        "prompt.other": "%@ asks",
        "prompt.retry": "The previous password was rejected.",
        "prompt.save": "Save in Keychain",
        "prompt.login": "Log In",
        "prompt.yes": "Trust and Connect",
        "prompt.no": "Cancel",
        "prompt.saved": "Password saved in Keychain",
        "prompt.savefail": "Could not save the password in Keychain",

        "detail.password": "Password",
        "detail.password.saved": "saved in Keychain",
        "detail.password.forget": "Forget",

        "rdp.opened": "Opened in Windows App — enter the password there (Windows App remembers it).",
        "rdp.missing.title": "Windows App is not installed",
        "rdp.missing.msg": "On a Mac, RDP connections are opened by the free Microsoft Windows App (formerly Microsoft Remote Desktop). Install it from the App Store and connect again.",
        "rdp.missing.store": "Open App Store",
        "rdp.export": "Export .rdp File…",
        "rdp.import": "Import .rdp File…",
        "btn.close": "Close",
        "edit.sec.rdp": "Remote desktop",
        "f.rdp.clipboard": "Share clipboard",
        "f.rdp.drives": "Share drives",
        "f.rdp.admin": "Administrative session (/admin)",
        "f.rdp.auth": "Server certificate",
        "f.rdp.auth.warn": "Warn (recommended)",
        "f.rdp.auth.require": "Require valid",
        "f.rdp.auth.none": "Do not check",
        "f.rdp.gateway": "RD Gateway",
        "f.rdp.app": "RemoteApp",
        "f.rdp.app.ph": "program or ||alias (empty = desktop)",
        "f.rdp.hint": "The connection opens in Microsoft Windows App. The Windows version reads the same settings.",

        "act.files": "Files (SFTP)",
        "files.connecting": "Connecting…",
        "files.failed": "Could not connect",
        "files.cancelled": "Cancelled",
        "files.up": "Enclosing folder",
        "files.refresh": "Refresh",
        "files.newfolder": "New Folder",
        "files.newfolder.ph": "Folder name",
        "files.upload": "Upload…",
        "files.upload.button": "Upload",
        "files.download": "Download…",
        "files.download.button": "Download Here",
        "files.delete": "Delete…",
        "files.rename": "Rename",
        "files.open": "Open",
        "files.openfolder": "Open Folder",
        "files.copypath": "Copy Path",
        "files.col.name": "Name",
        "files.col.size": "Size",
        "files.col.modified": "Modified",
        "files.col.mode": "Permissions",
        "files.count": "Items: %ld",
        "files.items": "%ld items",
        "files.uploading": "Uploading: %@",
        "files.uploaded": "Uploaded: %@",
        "files.downloading": "Downloading: %@",
        "files.downloaded": "Downloaded %@ to %@",
        "files.deleting": "Deleting…",
        "files.deleted": "Deleted items: %ld",
        "files.delete.one": "Delete “%@”?",
        "files.delete.many": "Delete %ld items?",
        "files.delete.msg": "Folders are deleted with their contents. This cannot be undone.",
        "files.overwrite.title": "Replace existing items?",
        "files.overwrite.msg": "This folder already contains: %@. Replace them?",
        "files.overwrite.confirm": "Replace",
        "files.err.denied": "Permission denied.",
        "files.err.missing": "No such file or folder.",
        "files.err.disconnected": "The connection was lost.",
        "files.err.name": "The name cannot be empty or contain “/”.",
        "files.err.exists": "“%@” already exists in this folder.",

        "files.edit": "Edit in Waypoint  ⌘E",
        "edit.loading": "Loading editor…",
        "edit.wrap": "Word wrap",
        "edit.reload": "Reload from server",
        "edit.savecopy": "Save a copy to disk…",
        "edit.yes": "Yes",
        "edit.discard": "Don't Save",
        "edit.ro.text": "The file belongs to %@ with permissions %@ — your account most likely cannot change it, so it was opened read-only. You can edit and save with sudo, or save a copy to disk.",
        "edit.ro.anyway": "Edit anyway",
        "edit.ro.status": "The file is open read-only.",
        "edit.ro.short": "read-only",
        "edit.note.latin1": "The file is not UTF-8 — opened as Latin-1; saving keeps that encoding.",
        "edit.note.mixed": "The file has mixed line endings — saving will normalize them to %@.",
        "edit.shutdown": "Unsaved changes in open editors: %ld. Quit without saving?",
        "edit.latin1.ask": "The character “%@” cannot be stored in Latin-1, the encoding of this file. Save the file as UTF-8?",
        "edit.nochange": "No changes — nothing to save.",
        "edit.saving": "Saving…",
        "edit.conflict": "“%@” has changed on the server since you opened it (now: %@, %@). Saving will overwrite those changes. Save anyway?",
        "edit.conflict.kept": "Not saved — the file on the server changed in the meantime. Your version is still in the editor.",
        "edit.saved": "Saved %@.",
        "edit.saved.inplace": "Saved %@ — in place, because %@.",
        "edit.fb.dir": "the folder is not writable",
        "edit.fb.owner": "a replace would change the file owner",
        "edit.fb.group": "a replace would change the file group",
        "edit.fb.rename": "the server does not support atomic replace",
        "edit.fail.denied": "You do not have permission to write this file. The file on the server is untouched and your changes are still in the editor.\n\nSaving with sudo will come in a later version. For now you can save a copy to disk.",
        "edit.fail.safe": "Could not save: %@\n\nThe file on the server is untouched. Your changes are still in the editor — you can retry (⌘S).",
        "edit.fail.damaged": "Saving was interrupted: %@\n\nThe file on the server may have been truncated! Your full version is in the editor — save again (⌘S) once the connection is back, or save a copy to disk.",
        "edit.fail.short": "Not saved — the file on the server is untouched.",
        "edit.fail.damaged.short": "Save interrupted — the file on the server may be truncated. Save again.",
        "edit.copysaved": "Copy saved: %@",
        "edit.reload.ask": "Reload the file from the server? Unsaved changes will be lost.",
        "edit.reloading": "Loading from server…",
        "edit.reloaded": "Reloaded from server %@.",
        "edit.close.ask": "Save changes to “%@” before closing?",
        "edit.toobig": "The file is too large to edit (limit %@). Download it or open it in another app.",
        "edit.binary": "This is a binary file — the editor only handles text files.",
        "edit.pos": "Ln %ld, Col %ld",
        "edit.sel": "(%ld selected)",

        "edit.ro.sudo": "Edit and Save with sudo",
        "edit.sudo.short": "sudo",

        "menu.go": "Go",
        "menu.terminal": "Terminal",
        "pal.open": "Command Palette…",
        "pal.placeholder": "Server, tab, action, or user@host to quick connect",
        "pal.tabs": "Tab",
        "pal.servers": "Server",
        "pal.actions": "Action",
        "pal.quick": "Connect to “%@”",
        "pal.quick.section": "Quick connect",
        "pal.quickmenu": "Quick Connect…",
        "snip.title": "Snippets",
        "snip.menu.pick": "Send Snippet…",
        "snip.menu.manage": "Manage Snippets…",
        "snip.filter": "Search snippets",
        "snip.empty": "No snippets",
        "snip.empty.desc": "A snippet is a saved command sent to the terminal with one shortcut, with server variables: {host}, {user}…",
        "snip.noterminal": "No active terminal",
        "snip.target": "To: %@",
        "snip.noenter": "No Enter — types only",
        "snip.new": "New snippet",
        "snip.name": "Name",
        "snip.command": "Command",
        "snip.vars": "Variables:",
        "snip.sendenter": "Send Enter at the end",
        "snip.hint": "⌥⌘1…9 sends the snippet with that number",
        "tab.duplicate": "Duplicate Tab",
        "term.find": "Find in Terminal…",
        "term.zoomin": "Bigger Font",
        "term.zoomout": "Smaller Font",
        "term.zoomreset": "Default Font Size",
        "edit.sudo.ask": "Your account cannot write this file. Save it as root with sudo? The file owner and permissions are kept.",
        "edit.sudo.yes": "Save with sudo",
        "edit.sudo.saving": "Saving with sudo…",
        "edit.sudo.saved": "Saved %@ with sudo.",
        "edit.sudo.saved.inplace": "Saved %@ with sudo — in place (server without GNU coreutils or no room for a file next to it).",
        "edit.sudo.prompt": "[sudo] password for %@ on %@",

        "edit.fb.ftp": "FTP has no atomic replace",
        "files.err.cancelledLogin": "Login cancelled.",
        "files.err.login": "The server rejected the login or password.",
        "files.err.cert": "The server certificate cannot be verified (%@). If this is your server with a self-signed certificate, you can trust it.",
        "files.cert.trust": "Trust This Server's Certificate",
        "files.cert.trust.help": "The connection stays encrypted, but without checking who issued the certificate. Applies to this server only.",

        "btn.ok": "OK",
        "group.rename": "Rename group…",
        "group.rename.title": "Rename group",
        "group.rename.msg": "New name for “%@” (applies to all its servers):",
        "group.collapse": "Collapse",
        "group.expand": "Expand",
        "group.moveto": "Move to group",
        "group.new": "New group…",
        "group.new.title": "New group",
        "group.new.msg": "Group name:",
        "reach.online": "Reachable · %d ms",
        "reach.online.short": "Reachable",
        "reach.offline": "Unreachable",
        "dash.title": "Dashboard",
        "dash.servers": "Servers",
        "dash.online": "Reachable",
        "dash.connects": "Connections (%d days)",
        "dash.quick.placeholder": "Quick connect: user@host[:port] (port 3389 = RDP)",
        "dash.recent": "Recently used",
        "dash.recent.help": "Connect to %@",
        "dash.activity": "Activity — last %d days",
        "dash.day": "Day",
        "dash.count": "Connections",
        "dash.top": "Most used",
        "log.reveal": "Show connection log",
        "log.empty": "The connection log is still empty",
        "set.list": "Server list",
        "set.reach": "Check server reachability in the background",
        "set.reach.interval": "Every",
        "set.reach.timeout": "Probe timeout",
        "set.seconds": "%d s",
        "set.latency": "Show latency (ms) in the list",
        "set.connections": "Connections",
        "set.confirmclose": "Ask before closing an active connection",
        "set.log": "Keep a connection log (no passwords)",
    ]

    /// Język interfejsu: polski, gdy jest pierwszym preferowanym językiem systemu, w przeciwnym razie angielski.
    public static let current: [String: String] = {
        let first = Locale.preferredLanguages.first?.lowercased() ?? "en"
        return first.hasPrefix("pl") ? pl : en
    }()
}

/// Tekst interfejsu po kluczu; brakujący klucz widać od razu (zamiast pustej etykiety).
public func L(_ key: String) -> String {
    Strings.current[key] ?? Strings.en[key] ?? key
}
